"""`PROGRESS.md` — the human-readable run record.

Regenerated after every phase. It answers, without anyone running a command:
where did the build get to, what did it cost, and — the part that matters most —
**what was cut**.

Scope trims are the reason this file is not optional. A graph that silently
covered less than it claimed would be worse than a small graph that says so, and
the capstone is instructed to read this file and name its trims in the
limitations section.
"""

from __future__ import annotations

import datetime as _dt
from pathlib import Path

from .budget import Budget
from .manifest import Manifest
from .state import RunState

PHASE_NAMES = {
    0: "Scoping and acquisition",
    1: "Reading notes",
    2: "Claims extraction",
    3: "Edge construction",
    4: "Structural analysis",
    5: "Capstone",
}

_STATUS_MARK = {
    "done": "✅",
    "running": "🔄",
    "pending": "⬜",
    "failed": "❌",
    "skipped": "⏭️",
}


def update_progress(
    project_dir: Path | str, manifest: Manifest, state: RunState, budget: Budget
) -> Path:
    path = Path(project_dir) / "PROGRESS.md"
    path.write_text(render(manifest, state, budget), encoding="utf-8")
    return path


def render(manifest: Manifest, state: RunState, budget: Budget) -> str:
    today = _dt.date.today().isoformat()
    lines = [
        "---",
        "tags:",
        "  - type/progress",
        f"  - {manifest.tag}",
        f"created: {state.created[:10] or today}",
        f"updated: {today}",
        "---",
        "",
        f"# {manifest.project} — Progress",
        "",
        f"*Generated by `oskg`. Regenerated after every phase; hand edits are overwritten.*",
        "",
        f"**Question:** {manifest.question}",
        "",
        _budget_block(manifest, budget),
        "",
        "## Phases",
        "",
        "| Phase | Status | Items | Spend |",
        "|---|---|---|---|",
    ]

    for number, name in PHASE_NAMES.items():
        ps = state.phases.get(number)
        status = ps.status if ps else "pending"
        counts = ps.counts() if ps else {}
        items = " · ".join(f"{v} {k}" for k, v in sorted(counts.items())) or "—"
        spend = budget.ledger.spent_in_phase(number)
        lines.append(
            f"| {number}. {name} | {_STATUS_MARK.get(status, status)} {status} | {items} | ${spend:.2f} |"
        )

    lines += ["", _trims_block(state), "", _notes_block(state), "", _ledger_block(budget)]
    return "\n".join(lines).rstrip() + "\n"


def _budget_block(manifest: Manifest, budget: Budget) -> str:
    spent, total = budget.spent(), manifest.total_usd
    pct = (spent / total * 100) if total else 0
    filled = int(pct / 5)
    bar = "█" * filled + "░" * (20 - filled)
    return (
        f"## Budget\n\n"
        f"`{bar}` **${spent:.2f} / ${total:.2f}** ({pct:.0f}%) across "
        f"{budget.ledger.call_count()} calls"
        + (f", {budget.ledger.failure_count()} failed" if budget.ledger.failure_count() else "")
    )


def _trims_block(state: RunState) -> str:
    """Scope removed under budget pressure. The most important section here."""
    if not state.trims:
        return "## Scope trims\n\n_None — the full planned scope was covered._"

    lines = [
        "## Scope trims",
        "",
        "Work removed under budget pressure. **This is what the graph does not cover.**",
        "",
        "| Phase | Kind | Detail |",
        "|---|---|---|",
    ]
    for trim in state.trims:
        lines.append(f"| {trim['phase']} | {trim['kind']} | {trim['detail']} |")

    dropped: list[str] = []
    for trim in state.trims:
        value = trim.get("dropped")
        if isinstance(value, list):
            dropped.extend(str(v) for v in value)
    if dropped:
        lines += ["", "<details><summary>Dropped items</summary>", ""]
        lines += [f"- `{d}`" for d in dropped[:200]]
        if len(dropped) > 200:
            lines.append(f"- _({len(dropped) - 200} more)_")
        lines += ["", "</details>"]
    return "\n".join(lines)


def _notes_block(state: RunState) -> str:
    notes = [(n, note) for n, ps in sorted(state.phases.items()) for note in ps.notes]
    if not notes:
        return ""
    return "## Notes\n\n" + "\n".join(f"- **Phase {n}:** {note}" for n, note in notes)


def _ledger_block(budget: Budget) -> str:
    totals = budget.ledger.totals()
    by_phase = " · ".join(f"P{k} ${v:.2f}" for k, v in totals["by_phase"].items()) or "—"
    return (
        "## Ledger\n\n"
        f"- **Calls:** {totals['calls']} ({totals['failures']} failed)\n"
        f"- **Tokens:** {totals['input_tokens']:,} in · {totals['output_tokens']:,} out\n"
        f"- **API calls:** {totals['api_calls']:,}\n"
        f"- **By phase:** {by_phase}\n\n"
        "Full per-call detail is in `.oskg/ledger.jsonl` (`oskg status --ledger`)."
    )
